function [image_store, augmented_image_store] = load_images(...
    path,...
    output_size,...
    read_function)

    image_store = imageDatastore(...
        path ,...
        'IncludeSubfolders', true,...
        'LabelSource', 'foldernames',...
        'FileExtensions', '.JPEG');
    image_store.ReadFcn = read_function;
    
    augmented_image_store = augmentedImageDatastore(...
        output_size, image_store,...
        'ColorPreprocessing', 'gray2rgb');
end

