function [image_store, augmented_image_store] = load_images(...
    path,...
    output_size,...
    read_function)

    image_store = imageDatastore(...
        path ,...
        'IncludeSubfolders', true,...
        'LabelSource', 'foldernames',...
        'FileExtensions', '.JPEG');
    image_store.ReadFcn = read_function;
    
    pixel_range = [-30 30];
    scale_range = [0.9 1.1];
    
    image_augmenter = imageDataAugmenter( ...
        'RandXReflection', true,...
        'RandXTranslation', pixel_range, ...
        'RandYTranslation', pixel_range, ...
        'RandXScale', scale_range, ...
        'RandYScale', scale_range);
    
    augmented_image_store = augmentedImageDatastore(...
        output_size, image_store,...
        'DataAugmentation', image_augmenter, ...
        'ColorPreprocessing', 'gray2rgb');
end

