function [image_store] = load_images(path, output_size)
%LOAD_IMAGES Summary of this function goes here
%   Detailed explanation goes here
    imds = imageDatastore(...
        path ,...
        "IncludeSubfolders", true,...
        "LabelSource", "foldernames",...
        "FileExtensions", ".JPEG");

    imds.ReadFcn = @(location) imread(location);
    augmented_imds = augmentedImageDatastore(...
        output_size, imds,...
        "ColorPreprocessing", "gray2rgb");
    image_store = augmented_imds;
end

